version: "3.9"

services:
  app:
    container_name: flask_app-solectric
    build:
      context: .
      dockerfile: Dockerfile  # Asegúrate de que se llama así o cámbialo aquí
    ports:
      - "5000:5000"
    volumes:
      - .:/app